


<html>
    <head>
        <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet" media="screen">
        
    </head>
    <body>

        <?php
        $form = new Application_Form_UserDetails();



        echo $form;
        ?>
    </body>
    <script src="<?php echo $this->baseUrl() ?>/js/jquery-2.1.3.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/bootstrap.min.js"></script>
</html>

