<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="UTF-8" >
        <?php
            echo $this->headMeta();
            echo $this->headTitle();
            echo $this->headLink();
        ?>
        <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl() ?>/css/jquery-ui.min.css" rel="stylesheet" media="screen">

    </head>
    <body>

        <?php echo $this->layout()->content; ?>


    </body>
    <?php echo $this->headScript(); ?>
    <script src="<?php echo $this->baseUrl() ?>/js/jquery-2.1.3.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/js/bootstrap.min.js"></script>

</html>