<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Coding4all</title>
        <meta name="description" content="description">
        <meta name="author" content="Coding4all">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="<?php echo $this->baseUrl() ?>/admin1/plugins/bootstrap/bootstrap.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl() ?>/admin1/plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet">
        <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->baseUrl() ?>/admin1/plugins/fancybox/jquery.fancybox.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl() ?>/admin1/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl() ?>/admin1/plugins/xcharts/xcharts.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl() ?>/admin1/plugins/select2/select2.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl() ?>/admin1/css/style.css" rel="stylesheet">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
                        <script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
                        <script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
        <![endif]-->
        
         <script src="<?php echo $this->baseUrl() ?>/admin1/plugins/jquery/jquery-2.1.0.min.js"></script>
        <!--<script src="<?php echo $this->baseUrl() ?>/admin1/plugins/jquery-ui/jquery-ui.min.js"></script>-->
         <!--<script src="<?php echo $this->baseUrl() ?>/admin1/js/devoops.js"></script>-->
    </head>
    <body>
        <!--Start Header-->
        <div id="screensaver">
            <canvas id="canvas"></canvas>
            <i class="fa fa-lock" id="screen_unlock"></i>
        </div>
        <div id="modalbox">
            <div class="devoops-modal">
                <div class="devoops-modal-header">
                    <div class="modal-header-name">
                        <span>Basic table</span>
                    </div>
                    <div class="box-icons">
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="devoops-modal-inner">
                </div>
                <div class="devoops-modal-bottom">
                </div>
            </div>
        </div>
        <header class="navbar">
            <div class="container-fluid expanded-panel">
                <div class="row">
                    <div id="logo" class="col-xs-12 col-sm-2">
                        <a href="<?php echo $this->baseUrl() ?>/admin1/">Coding4all</a>
                    </div>
                    <div id="top-panel" class="col-xs-12 col-sm-10">
                        <div class="row">
                            <div class="col-xs-8 col-sm-4">
                                <a href="#" class="show-sidebar">
                                    <i class="fa fa-bars"></i>
                                </a>
                                
                            </div>
                            <div class="col-xs-4 col-sm-8 top-panel-right">
                                <ul class="nav navbar-nav pull-right panel-menu">
                                    
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle account" data-toggle="dropdown">
                                            <div class="avatar">
                                                <img src="<?php echo $this->baseUrl() ?>/admin1/img/avatar.jpg" class="img-rounded" alt="avatar" />
                                            </div>
                                            <i class="fa fa-angle-down pull-right"></i>
                                            <div class="user-mini pull-right">
                                                <span class="welcome">Welcome,</span>
                                                <span><?php echo $this->admin->name; ?></span>
                                            </div>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-user"></i>
                                                    <span>Profile</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-power-off"></i>
                                                    <span>Logout</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!--End Header-->
        <!--Start Container-->
        <div id="main" class="container-fluid">
            <div class="row">
                <div id="sidebar-left" class="col-xs-2 col-sm-2">
                    <ul class="nav main-menu">
                        <li>
                            <a href="<?php echo $this->baseUrl() ?>/admin/statistics/view" class="active">
                                <i class="fa fa-dashboard"></i>
                                <span class="hidden-xs">Statistics</span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">
                                <i class="fa fa-users"></i>
                                <span class="hidden-xs">Users</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl() ?>/admin/user/add">Add</a></li>
                                <li><a href="<?php echo $this->baseUrl() ?>/admin/user/list">View</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">
                                <i class="fa fa-book"></i>
                                <span class="hidden-xs">Categories</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl() ?>/admin/category/add">Add</a></li>
                                <li><a href="<?php echo $this->baseUrl() ?>/admin/category/list">View</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">
                                <i class="fa fa-certificate"></i>
                                <span class="hidden-xs">Courses</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl() ?>/admin/course/add">Add</a></li>
                                <li><a href="<?php echo $this->baseUrl() ?>/admin/course/list">View</a></li>
                            </ul>
                        </li>
                         <li>
                            <a href="<?php echo $this->baseUrl() ?>/admin/request/list" class="active">
                                <i class="fa fa-thumbs-up"></i>
                                <span class="hidden-xs">Requests</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!--Start Content-->
                <div id="content" class="col-xs-12 col-sm-10">
                    <div class="preloader">
                        <img src="<?php echo $this->baseUrl() ?>/admin1/img/devoops_getdata.gif" class="devoops-getdata" alt="preloader"/>
                    </div>
                    <div id="ajax-content1">

                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
                <!--End Content-->
            </div>
        </div>
        <!--End Container-->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <!--<script src="http://code.jquery.com/jquery.js"></script>-->
        <script src="<?php echo $this->baseUrl() ?>/admin1/plugins/jquery/jquery-2.1.0.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/admin1/plugins/jquery-ui/jquery-ui.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="<?php echo $this->baseUrl() ?>/admin1/plugins/bootstrap/bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/admin1/plugins/justified-gallery/jquery.justifiedgallery.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/admin1/plugins/tinymce/tinymce.min.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/admin1/plugins/tinymce/jquery.tinymce.min.js"></script>
        <!-- All functions for this theme + document.ready processing -->
        <script src="<?php echo $this->baseUrl() ?>/admin1/js/devoops.js"></script>
    </body>
</html>
