<?php echo $this->doctype(); ?>

<html>
    <head>
        <?php
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        ?>
        <meta charset="UTF-8" >
        <!--<link href="<?php echo $this->baseUrl() ?>/admin1/css/style.css" rel="stylesheet">-->
        <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <!--<link href="<?php echo $this->baseUrl() ?>/css/jquery-ui.min.css" rel="stylesheet" media="screen">-->
        <!--<link href="<?php echo $this->baseUrl() ?>/css/theme-bootstrap.min.css" rel="stylesheet" media="screen">-->
        <link href="<?php echo $this->baseUrl() ?>/css/bootstrap-theme.min.css" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl() ?>/css/font-awesome.min.css" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl() ?>/css/style.css" rel="stylesheet" type="text/css"/>
        
        
    </head>
    <body style="padding-top: 60px; padding-bottom: 100px;">
        <div class ="container">
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->baseUrl() ?>">Coding4all.com</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->baseUrl() ?>">Home<span class="sr-only">(current)</span></a></li>
<!--                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Programming</a></li>
                                    <li><a href="#">Web Development</a></li>
                                </ul>
                            </li>
                            <li><a href="">Courses</a></li>-->
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <?php if(!$this->user) { ?>
                            <li><a href="<?php echo $this->baseUrl() ?>/student/register"><span class="glyphicon glyphicon-registration-mark"></span> Register</a></li>
                            <li><a href="<?php echo $this->baseUrl() ?>/student/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            <?php } else { ?>
                            <li class="dropdown">
                                        <a href="#" class="dropdown-toggle account" data-toggle="dropdown">
                                            <div class="avatar">
                                                <img src="<?php echo $this->baseUrl(). $this->user->pic ?>" class="img-rounded" alt="avatar" />
                                            </div>
                                            <i class="fa fa-angle-down pull-right"></i>
                                            <div class="user-mini pull-right">
                                                <span class="welcome">Welcome,</span><br />
                                                <span><?php echo $this->user->name; ?></span>
                                                
                                            </div>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-user"></i>
                                                    <span>Profile</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->baseUrl() ?>/student/logout">
                                                    <i class="fa fa-power-off"></i>
                                                    <span>Logout</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li><a href="<?php echo $this->baseUrl() ?>/admin/"><span class="glyphicon glyphicon-lock"></span> Admin</a></li>
                            <?php } ?>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>

        </div>
        <?php echo $this->layout()->content; ?>
        <nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="container-fluid ">

                <ul class="nav navbar-nav">
                    <li><a>Copyright © 2015 Coding4all.com</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.facebook.com/coding4all" class="btn btn-social-icon btn-facebook hidden-xs"><i class="fa fa-facebook-official"></i> Facebook</a></li>
                </ul>
            </div>
        </nav>
    </body>
    <?php echo $this->headScript(); ?>
    <script src="<?php echo $this->baseUrl() ?>/js/jquery-2.1.3.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/js/bootstrap.min.js"></script>

</html>