
<?php

$cats = $this->cat;
?>


<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Edit User</h4>
            </div>
            <div class="modal-body">
<?php echo $this->form; ?>
                <br /><br /><br />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" name="save">Save changes</button>
            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-user"></i>
                    <span>Categories List</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-1">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Start: list_row -->

<?php foreach ($cats as $cat) { ?>
                            <tr>
                                <td><?php echo $cat["id"] ?></td>
                                <td><?php echo $cat["name"] ?></td>
                                
                                <td>

                                    <button class="btn btn-primary" name="edit" value="<?php echo $cat["id"] ?>"><span class="fa fa-pencil-square-o"</button>
                                    <button class="btn btn-danger" name="del" value="<?php echo $cat["id"] ?>"><span class="fa fa-trash-o"</button>
                                </td>
                            </tr>
<?php } ?>
                        <!-- End: list_row -->
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script>

    $("[name=del]").click(Delete);


    function Delete(event) {
        e = event.target;
        var ajaxRequest = new XMLHttpRequest();

        ajaxRequest.open('POST', '<?php echo $this->baseUrl() ?>/admin/category/delete', true);
        ajaxRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");


        ajaxRequest.send("id=" + e.value);
            alert(e.value);
        ajaxRequest.onreadystatechange = function () {
            if (ajaxRequest.readyState === 4 && ajaxRequest.status === 200) {

                var text = ajaxRequest.responseText.trim();
//          alert(text);
                if (text > 0) {
                    e.parentNode.parentNode.remove();
                }
                else {
                    alert("Couldn't Delete");
                }

            }
        };

    }

    $("[name=edit]").click(Edit);
    function Edit(event) {

        id = event.target.value;
//        $('.modal-body').html(id);
        var target = $( event.target.parentNode.parentNode );
        var text = target.contents().filter(function () {
            return this.nodeType != 3;
        });
        
        $('#id').attr('value', $(text[0]).text());
        $('#name').attr('value', $(text[1]).text());
        
        $("#myModal").modal('show');

    }

    $("[name=save]").click(Save);
    function Save(event) {
//        alert("saved");

        e = event.target;
        var ajaxRequest = new XMLHttpRequest();

        ajaxRequest.open('POST', '<?php echo $this->baseUrl() ?>/admin/category/edit', true);
        ajaxRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        
        var str = "id=" + id + 
                "&name="+$('#name').val();
        
//        alert(str);

        ajaxRequest.send(str);

        ajaxRequest.onreadystatechange = function () {
            if (ajaxRequest.readyState === 4 && ajaxRequest.status === 200) {

                var text = ajaxRequest.responseText.trim();
//          alert(text);
                if (text > 0) {
                    e.parentNode.parentNode.remove();
                }
                else {
                    alert("Couldn't Update");
                }
                $("#myModal").modal('hide');
            }
            
        };
    }

</script>
